spring:
  datasource: # configurações de datasource do Spring, especificando banco e usuário.
    url: jdbc:h2:mem:sdw2025
    username: sdw2025
    password:
  jpa:
    show-sql: true # conf. para deixar querys mais verbosas (visualizacao no log)
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop (cria as tabelas no primeiro momento)
    properties:
      hibernate:
        format_sql: true
  h2: # conf. do h2 para disponiblizar um console dele e acessar o banco via browser.
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

# Para rodar o profile dev que foje do padrão(application.yml) deve se criar uma variavel de ambiente. (environment variables)
# SPRING_PROFILES_ACTIVE=dev
